accounts:
  - name: alice
    coins: ["20000token", "200000000udepos"]
  - name: bob
    coins: ["10000token", "100000000udepos"]
build:
  binary: "deposd"
  main: "cmd/deposd"
validator:
  name: alice
  staked: "100000000udepos"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000udepos"]
genesis:
  chain_id: "depos-localnet-1"
  app_state:
    staking:
      params:
        bond_denom: "udepos"
init:
  home: "$HOME/.deposd"
